config/routes.rb
Rails.application.routes.draw do
  resources :accounts
  resources :employees do
    resources :time_entries 
  end

end

app/models/account.rb
class Account < ActiveRecord::Base
	has_many :account_entries, dependent: :destroy

	validates :name, presence: true, length: {in: 1..70}, uniqueness: true
end

app/models/account_entry.rb
class AccountEntry < ActiveRecord::Base
	belongs_to :account

	validates :account_id, presence: true
	validates_associated :account

	state_machine :state, initial: :submitted do
		
		event :approve do
			transition submitted: :approved
		end

		event :reject do
			transition submitted: :rejected
		end
	end
end

app/models/customer.rb
class Customer < Account
	has_many :time_entries

	# scope :premier, ->(name) { where("name like ?", name + "%")}
	scope :newest, ->{ order("created_at DESC")}
	def self.premier
		where('name like ?', 'a%')
	end
end

app/models/employee.rb
class Employee < Account
	has_many :time_entries
	has_and_belongs_to_many :projects

	def total_hours
		time_entries.sum(:time)
	end

	def log_time(amount, customer)
		TimeEntry.create(time: amount, employee: self, account: customer)
	end
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :customer
  has_and_belongs_to_many :employees

  validates :name, presence: true, length: {in: 1..70, message: "Please. use a decent name"}, uniqueness: true
end

app/models/time_entry.rb
class TimeEntry < AccountEntry
	belongs_to :employee

	validates :time, numericality: {greater_than: 0, less_than: 24}

	before_create :calculate_amount!
	

	def self.per_hour
		34
	end

	def calculate_amount!
		self.amount = TimeEntry.per_hour * self.time
	end

	def update_account_balance
		account.balance = account.time_entries.sum(:amount)
		account.save
	end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
	def index
		@accounts = Customer.all
	end

	def show
		@account = Account.find(params[:id])
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
	def index
		@employees = Employee.all
	end

	def show
		@employee = Employee.find(params[:id])
	end

	def create
		e = Employee.create(employee_params)
		redirect_to employee_path(e)
	end

	private
		def employee_params
			params.require(:employee).permit(:name)
		end
end

app/controllers/time_entries_controller.rb
class TimeEntriesController < ApplicationController
	def create
		e = Employee.find params[:employee_id]
		t = e.time_entries.create(time_entries_params)
		redirect_to employee_path(e)
	end

	private

		def time_entries_params
			params.require(:time_entry).permit(:time, :account_id, :state)
		end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/time_entries_helper.rb
module TimeEntriesHelper
end

app/views/accounts/index.html.erb
<ul>
	<% @accounts.each do |account| %>
		<li>
			<%= link_to account.name, account_path(account) %> |
			<%= account.type %>
		</li>		
	<%end%>
</ul>

app/views/accounts/show.html.erb
<h1><%= @account.name %></h1>

Total Hours: <%= @account.account_entries.sum(:time) %>
Total Cost: $<%= (@account.account_entries.map &:cost).sum %>

<h4>Account Entries</h4>

<table>
	<% @account.account_entries.each do |entry| %>
	<tr>
		<td><%= entry.created_at %></td>
		<td><%= entry.employee.name %></td>
		<td><%= entry.time %> hours</td>
	</tr>
	<% end %>
</table>

app/views/employees/index.html.erb
<ul>
	<% @employees.each do |employee| %>
		<li>
			<%= link_to employee.name, employee_path(employee) %> |
			<%= employee.type %>
		</li>		
	<%end%>
</ul>
<%= form_for Employee.new do |f| %>
	<%= f.text_field :name %>
	<%= f.submit %>
<%end%>

app/views/employees/show.html.erb
<%= @employee.name %>

<h3>Submit time form </h3>
<%= form_for [@employee, TimeEntry.new] do |f| %>
	<%= f.label :customer %>
	<%= f.collection_select(:account_id, Customer.all, :id, :name)%>
	<%= f.label :time %>
	<%= f.text_field :time, value: 1.0 %>
	<%= f.submit %>
<%end%>

<h3>Time Entries</h3>
<% @employee.time_entries.each do |entry| %>
	<div class='entry'>
		<strong><%= entry.state %></strong>
		<%= entry.time %>
		<%= entry.account.name %>
		<%= entry.created_at %>
	</div>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Biller</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>